services:
  spotify:
    image: billwan96/spotify:tagname
    ports:
      - "8787:8787"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/arm64